name: React build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      REACT_APP_DAILY_CORONA_STATUS_API_SERVICE_KEY: ${{secrets.REACT_APP_DAILY_CORONA_STATUS_API_SERVICE_KEY}}
    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: Instal Dependencies
        run: npm install

      - name: Build
        run: CI=false npm run build